name: flutter-tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  lint: ^1.5.3
